### ISSUE TITLE
How to use this library?

### ISSUE THREAD

**Issue by jason0597** [jbop1626/ninty-233#1]
Hi, I'm working on [a 3DS project](https://github.com/jason0597/TADPole-3DS) that requires me to sign 2 SHA256 hashes using sect233r1.
I wanted to ask, how specifically is this library supposed to be used? I thought about cloning the repo and building a `.a` file out of everything inside the `src` folder, but is that how it was meant to be built?
Are you supposed to modify your own project's Makefile so that it searches for `.cpp` file recursively?
And what about header files? Normally in a 3DS project you're meant to have an `include` folder that contains `.h` files exclusively, yet this project has header files mixed in with the source itself.

**Comment by jbop1626** [comment]
Howdy, I made this rather quickly to help with some iQue Player projects, so it's a little haphazard other than the general ECC and ECDH implementation (which in contrast I spent a lot of time on). Because of that I was generally using it in the second way you mention, and just including all the files themselves to be quick. However, I have also used it just fine as a static lib, making it exactly the way you suggest. I would definitely recommend doing that, but really it's up to you how to use it.  

If you make a lib then the headers shouldn't be a problem. If you want to go the other route, it should still be easy to stick all the headers into your include directory, and then slightly modify the headers to point to the right place.  

I also think you may have to modify things a (tiny) bit to make it sign SHA256 hashes rather than SHA1.

**Comment by jason0597** [comment]
What modifications would be needed to sign SHA256 hashes? From looking at the code, the `ecdsa_sign()` function takes in a `BigUnsigned hash` input as the hash to sign. SHA1 is 160 bits while SHA256 is 256 bits. Is there a limitation to this `BigUnsigned` class?

Actually, how exactly would you feed in a custom hash to the `ecdsa_sign()` function? Hashes are usually generated in the form of byte arrays, and you'd need to convert that hash into a `BigUnsigned`. However, the `BigUnsigned` constructor/assignment methods are hidden deep inside the seperate folder and are not exposed to the outside by the `ninty-233.cpp` file. Would I have to include the [BigUnsigned](https://mattmccutchen.net/bigint/) library to my project manually so that I have access to the constructors I need so that I can pass the objects that ninty-233 requires?

From my understanding this project wasn't meant to be used outside of its SHA1 usage which is why SHA1 is built-in and integrated better than external data to be signed, is this correct?

**Comment by jbop1626** [comment]
You're correct that I wasn't intending non-SHA1 usage (since the Wii and iQue Player only use that), however I don't think it would take too much work to make it use SHA256. You'll have to supply an SHA256 implementation though. [WjCryptLib](https://github.com/WaterJuice/WjCryptLib), from which I got the SHA1 implementation, also seems to have one for SHA256. I'd check that out, especially since the API is probably similar.  

You can see at the bottom of the `sha1` function in [ninty-233.cpp](https://github.com/jbop1626/ninty-233/blob/master/src/ninty-233.cpp#L63) how I converted a byte array into a BigUnsigned; you should be able to change that loop to run over 32 bytes rather than 20 and have it work fine. Also the BigInteger library is only limited by how much memory you have on the machine.  

In summary, off the top of my head you'd need to do 2-3 things to make SHA256 work:

1. Get an SHA256 implementation, e.g. [this](https://github.com/WaterJuice/WjCryptLib/blob/master/lib/WjCryptLib_Sha256.c) plus [this](https://github.com/WaterJuice/WjCryptLib/blob/master/lib/WjCryptLib_Sha256.h) (unless you already have one, of course).
2. Alter/replace the `sha1` function to use SHA256 instead.
3. [*possibly won't need to do*] Modify or create a new `generate_k` function. The only reason you'd need to create a new one is if you want the signatures to be secure (probably not, if you're resigning homebrew or something). You *may* need to modify things a tiny bit to handle the extra length of an SHA256 hash, but I actually don't think so.

Two final things to keep in mind:  

1. The ECC keys expect padding (i.e. 32-byte private keys and 64-byte public), which is default on the iQue Player but not on the Wii. I don't know what format you're using but it should be trivial to add a few zero bytes to a byte array if necessary. I explain it a bit more [here](https://github.com/jbop1626/ninty-233/blob/master/src/ecc/ecc.cpp#L317).
2. SHA1 hashes are 20-bytes, and therefore less than 233 bits. SHA256 hashes are larger, and therefore will have to be truncated to 233 bits before being used in the signing process. You should be able to `AND` the original BigUnsigned hash with 233 1 bits (using the normal bitwise operators, since they are overloaded in the BigUnsigned class) to do that easily.

**Comment by jason0597** [comment]
Something a bit unrelated, at [this line](https://github.com/jbop1626/ninty-233/blob/master/src/ecc/ecc.cpp#L67) you do a `std::memcpy()`, however when I compile this throws me a "memcpy is not a member of std" error. I also notice that you don't have a `#include <cstring>` at the top. Is it meant to be like that?

**Comment by jbop1626** [comment]
Nope it isn't supposed to be like that! Not sure how this worked without it; it must be included in iostream or iomanip and my compiler was OK with that :man_shrugging: 

Thanks for pointing it out, should be fixed now!

**Comment by jason0597** [comment]
Hi, sorry for leaving this issue open for so long.
As the project I've been working on has been finished, I'm closing this issue. Thanks for helping me out

**Comment by jbop1626** [comment]
Happy to help!
